version: '3.7'
services:
  primary:
    image: mysql:5.7
    command: --gtid-mode=ON --enforce-gtid-consistency=ON --server-id=1 --log-bin=mysql-bin --log-slave-updates --relay-log=relay-bin --init-file=/sql/setup-primary.sql
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure
    volumes:
    - ./sql:/sql:ro
  replica1:
    image: mysql:5.7
    command: --gtid-mode=ON --enforce-gtid-consistency=ON --server-id=2 --log-bin=mysql-bin --log-slave-updates --relay-log=relay-bin --init-file=/sql/setup-replica.sql --read-only=ON
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure
    volumes:
    - ./sql:/sql:ro
  replica2:
    image: mysql:5.7
    command: --gtid-mode=ON --enforce-gtid-consistency=ON --server-id=3 --log-bin=mysql-bin --log-slave-updates --relay-log=relay-bin --init-file=/sql/setup-replica.sql --read-only=ON
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure
    volumes:
    - ./sql:/sql:ro
  replica3:
    image: mysql:5.7
    command: --gtid-mode=ON --enforce-gtid-consistency=ON --server-id=3 --log-bin=mysql-bin --log-slave-updates --relay-log=relay-bin --init-file=/sql/setup-replica.sql --read-only=ON
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    restart: on-failure
    volumes:
    - ./sql:/sql:ro
  pt-heartbeat:
    image: yuuki0xff/percona-toolkit
    entrypoint: pt-heartbeat
    command: --update --create-table --host=primary --user=heartbeat --password=heartbeat --database=percona --interval=0.5 --check-read-only --no-version-check
    restart: on-failure
    depends_on:
    - primary
  proxysql:
    image: proxysql/proxysql:2.0.12
    command: --no-version-check --reload
    volumes:
    - ./etc/proxysql.cnf:/etc/proxysql.cnf:ro
    expose:
    - 3306
    - 6032
    restart: on-failure
    ports:
    - 6032:6032
    depends_on:
    - pt-heartbeat
    - primary
    - replica1
    - replica2
    - replica3
  freno:
    build:
      context: ./freno
    command: '--debug --http'
    expose:
    - 8111
    ports:
    - 8111:8111
    restart: on-failure
    volumes:
    - ./etc/freno.conf.json:/etc/freno.conf.json:ro
    depends_on:
    - proxysql
