version: '3.7'
services:
  master:
    image: mysql:5.7
    command: --gtid-mode=ON --enforce-gtid-consistency=ON --server-id=1 --log-bin=mysql-bin --log-slave-updates --relay-log=relay-bin
    environment:
    - MYSQL_ROOT_PASSWORD=123456
  replica1:
    image: mysql:5.7
    command: --gtid-mode=ON --enforce-gtid-consistency=ON --server-id=2 --log-bin=mysql-bin --log-slave-updates --relay-log=relay-bin --read-only=ON
    environment:
    - MYSQL_ROOT_PASSWORD=123456
  replica2:
    image: mysql:5.7
    command: --gtid-mode=ON --enforce-gtid-consistency=ON --server-id=3 --log-bin=mysql-bin --log-slave-updates --relay-log=relay-bin --read-only=ON
    environment:
    - MYSQL_ROOT_PASSWORD=123456
  pt-heartbeat:
    image: yuuki0xff/percona-toolkit:latest
    entrypoint: pt-heartbeat
    command: --update --create-table --host=master --user=root --password=123456 --database=percona --interval=0.25 --check-read-only --no-version-check
    depends_on:
    - master
  freno-db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=123456
  freno:
    build:
      context: .
      dockerfile: Dockerfile.freno
    command: '--config /etc/freno.json --debug --http'
    expose:
    - 8111
    ports:
    - 8111:8111
    volumes:
    - ./etc/freno.json:/etc/freno.json:ro
    depends_on:
    - freno-db
  proxysql:
    image: proxysql/proxysql:2.0.12
    command: --no-version-check --reload
    volumes:
    - ./etc/proxysql.cnf:/etc/proxysql.cnf:ro
    expose:
    - 3306
    - 6032
    depends_on:
    - master
    - replica1
    - replica2
