CREATE USER IF NOT EXISTS 'root'@'%';
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'root'@'%' = PASSWORD('123456');

STOP SLAVE;
CHANGE MASTER TO MASTER_HOST='primary', MASTER_PORT=3306, MASTER_USER='repl', MASTER_PASSWORD='repl', MASTER_AUTO_POSITION=1, MASTER_CONNECT_RETRY=1;
START SLAVE;
